/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment1;

import java.io.IOException;
import java.net.InetAddress;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Thien Nhan
 */
public class formSignIn extends javax.swing.JFrame {

    /**
     * Creates new form formSignIn
     */
    public formSignIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        pw = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        port = new javax.swing.JTextField();
        background = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(280, 483));
        getContentPane().setLayout(null);

        signin.setText("Sign In");
        signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinActionPerformed(evt);
            }
        });
        getContentPane().add(signin);
        signin.setBounds(90, 350, 100, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Password");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 160, 90, 17);

        id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        id.setForeground(new java.awt.Color(255, 255, 255));
        id.setText("ID");
        getContentPane().add(id);
        id.setBounds(40, 70, 30, 17);

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtID);
        txtID.setBounds(40, 100, 200, 30);
        getContentPane().add(pw);
        pw.setBounds(40, 190, 200, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Đăng Nhập");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 30, 150, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Port");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 240, 50, 20);
        getContentPane().add(port);
        port.setBounds(40, 270, 200, 30);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background-wallpapers-32.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 277, 460);

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void signinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinActionPerformed
        try {
           
            String id=txtID.getText().toString();
            String pass=pw.getText().toString();
           String ip=InetAddress.getLocalHost().toString();
           int porT=Integer.parseInt(port.getText().toString());
           ip=ip.split("/")[1];
          
             Http http = new Http();
               String kq = http.signIn(id, pass,ip,porT);
            if(kq.equals("success"))
            {
               
               
                    String[] session={ip+"/22222"};
              mainForm main=new mainForm(id,porT);
             this.setVisible(false);
             main.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Không thẻ đăng nhập, vui lòng thử lại");
            }
        } catch (IOException ex) {
            Logger.getLogger(formSignIn.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_signinActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JTextField port;
    private javax.swing.JTextField pw;
    private javax.swing.JButton signin;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
